# cruise-control-ui.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cruise-control-ui
  namespace: kafka-upgrade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cruise-control-ui
  template:
    metadata:
      labels:
        app: cruise-control-ui
    spec:
      containers:
      - name: cruise-control-ui
        image: densecravpfyifvv42u6.azurecr.io/cruise-control-ui:1.0
        ports:
        - containerPort: 80
        env:
        - name: CC_UI_BACKEND_HOST
          value: "my-cluster-cruise-control"
        - name: CC_UI_BACKEND_PORT
          value: "9090"
        - name: CC_UI_SERVER_PORT
          value: "80"
        - name: CC_UI_KAFKA_CLUSTER_NAME
          value: "my-cluster"
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: cruise-control-ui
  namespace: kafka-upgrade
spec:
  type: LoadBalancer
  selector:
   app: cruise-control-ui
  ports:
  - port: 8080
    targetPort: 80
